apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-triton
  labels:
    app.kubernetes.io/name: triton
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: triton
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: grpc
      port: 8001
      targetPort: grpc
    - name: metrics
      port: 8002
      targetPort: metrics
